version: '3.7'
services:
    client:
        build:
            context: .
        ports:
            - 80:80
        container_name: client
networks:
    default:
        external:
            name: teaclub
