version: '3.7'
services:
    client:
        build:
            context: ./client
        ports:
            - 80:80
    server:
        build:
            context: ./server
            target: development
        ports:
            - 5000:5000
        volumes:
            - "./server:/go/src/github.com/personal-website-server/"
        container_name: server
networks:
  default:
    external:
        name: teaclub
