version: '3.7'
services:
    server:
        build:
            context: .
        ports:
            - 5000:5000
            - 80:80
networks:
    default:
        external:
            name: teaclub
