version: '3.7'
services:
    client:
        build:
            context: .
            target: development
        ports:
            - 3000:3000
        volumes:
            - "./src:/app/src"
networks:
  default:
    external:
        name: teaclub
