version: '3.7'
services:
    server:
        build:
            context: .
            # Tells docker to only build the server stage in dockerfile
            target: server
        ports:
            - 5000:5000
        volumes:
            - "./server/rest:/go/src/github.com/personal-website-server/rest"
            - "./server/vendor:/go/src/github.com/personal-website-server/vendor"
            - "./server/main.go:/go/src/github.com/personal-website-server/main.go"
        container_name: server
networks:
  default:
    external:
        name: teaclub
